# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dialog_pathwalker.ui'
#
# Created by: PyQt4 UI code generator 4.12.dev1605051544
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogPathwalker(object):
    def setupUi(self, DialogModelVisualization):

        DialogModelVisualization.setObjectName(_fromUtf8("DialogModelVisualization"))
        DialogModelVisualization.resize(304, 338)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogModelVisualization.sizePolicy().hasHeightForWidth())
        DialogModelVisualization.setSizePolicy(sizePolicy)
        self.gridlayout = QtGui.QGridLayout(DialogModelVisualization)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.tabWidget = QtGui.QTabWidget(DialogModelVisualization)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))

        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButton_17 = QtGui.QPushButton(self.tab)
        self.pushButton_17.setMaximumSize(QtCore.QSize(16777215, 32))
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.gridLayout_3.addWidget(self.pushButton_17, 3, 2, 1, 1)
        self.pushButton_19 = QtGui.QPushButton(self.tab)
        self.pushButton_19.setMaximumSize(QtCore.QSize(16777215, 32))
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.gridLayout_3.addWidget(self.pushButton_19, 4, 2, 1, 1)
        self.listWidget = QtGui.QListWidget(self.tab)
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 192))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        self.gridLayout_3.addWidget(self.listWidget, 2, 3, 3, 1)
        self.pushButton_18 = QtGui.QPushButton(self.tab)
        self.pushButton_18.setMaximumSize(QtCore.QSize(16777215, 32))
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.gridLayout_3.addWidget(self.pushButton_18, 2, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.tab)
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_3.addWidget(self.label_25, 1, 3, 1, 1)
        self.lineEditAtomScore = QtGui.QLineEdit(self.tab)
        self.lineEditAtomScore.setMaximumSize(QtCore.QSize(16777215, 21))
        self.lineEditAtomScore.setObjectName(_fromUtf8("lineEditAtomScore"))
        self.gridLayout_3.addWidget(self.lineEditAtomScore, 0, 0, 1, 1)
        self.listWidget_2 = QtGui.QListWidget(self.tab)
        self.listWidget_2.setMaximumSize(QtCore.QSize(16777215, 192))
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.gridLayout_3.addWidget(self.listWidget_2, 2, 0, 3, 2)
        self.preprocessPushButton = QtGui.QPushButton(self.tab)
        self.preprocessPushButton.setMaximumSize(QtCore.QSize(16777215, 32))
        self.preprocessPushButton.setObjectName(_fromUtf8("preprocessPushButton"))
        self.gridLayout_3.addWidget(self.preprocessPushButton, 5, 0, 1, 4)
        self.pushButtonBrowseAtomScore = QtGui.QPushButton(self.tab)
        self.pushButtonBrowseAtomScore.setMaximumSize(QtCore.QSize(16777215, 32))
        self.pushButtonBrowseAtomScore.setObjectName(_fromUtf8("pushButtonBrowseAtomScore"))
        self.gridLayout_3.addWidget(self.pushButtonBrowseAtomScore, 0, 1, 1, 2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))

        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lineEdit_5 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout_6.addWidget(self.lineEdit_5, 4, 2, 1, 1)
        self.lineEdit_8 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout_6.addWidget(self.lineEdit_8, 7, 2, 1, 1)
        self.pushButton_20 = QtGui.QPushButton(self.tab_2)
        self.pushButton_20.setMaximumSize(QtCore.QSize(16777215, 32))
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.gridLayout_6.addWidget(self.pushButton_20, 1, 1, 1, 1)
        self.pushButton_21 = QtGui.QPushButton(self.tab_2)
        self.pushButton_21.setMaximumSize(QtCore.QSize(16777215, 32))
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.gridLayout_6.addWidget(self.pushButton_21, 2, 1, 1, 1)
        self.lineEdit_7 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.gridLayout_6.addWidget(self.lineEdit_7, 6, 2, 1, 1)
        self.label_26 = QtGui.QLabel(self.tab_2)
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_6.addWidget(self.label_26, 0, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_6.addWidget(self.label_9, 7, 0, 1, 1)
        self.lineEdit_6 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout_6.addWidget(self.lineEdit_6, 5, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_6.addWidget(self.label_6, 4, 0, 1, 1)
        self.listWidget_4 = QtGui.QListWidget(self.tab_2)
        self.listWidget_4.setMaximumSize(QtCore.QSize(16777215, 192))
        self.listWidget_4.setObjectName(_fromUtf8("listWidget_4"))
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_4.addItem(item)
        self.gridLayout_6.addWidget(self.listWidget_4, 1, 2, 3, 1)
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_6.addWidget(self.label_8, 6, 0, 1, 1)
        self.listWidget_3 = QtGui.QListWidget(self.tab_2)
        self.listWidget_3.setMaximumSize(QtCore.QSize(16777215, 192))
        self.listWidget_3.setObjectName(_fromUtf8("listWidget_3"))
        item = QtGui.QListWidgetItem()
        self.listWidget_3.addItem(item)
        self.gridLayout_6.addWidget(self.listWidget_3, 1, 0, 3, 1)
        self.pushButton_2 = QtGui.QPushButton(self.tab_2)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_6.addWidget(self.pushButton_2, 8, 1, 1, 1)
        self.pushButton_22 = QtGui.QPushButton(self.tab_2)
        self.pushButton_22.setMaximumSize(QtCore.QSize(16777215, 32))
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.gridLayout_6.addWidget(self.pushButton_22, 3, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        

        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout = QtGui.QGridLayout(self.tab_3)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_4 = QtGui.QPushButton(self.tab_3)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout.addWidget(self.pushButton_4, 10, 0, 1, 2)
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_9 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout.addWidget(self.lineEdit_9, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.tab_3)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 6, 0, 1, 2)
        self.spinBox_6 = QtGui.QSpinBox(self.tab_3)
        self.spinBox_6.setMinimum(1)
        self.spinBox_6.setProperty("value", 10)
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.gridLayout.addWidget(self.spinBox_6, 3, 3, 1, 1)
        self.line = QtGui.QFrame(self.tab_3)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 4, 0, 1, 2)
        self.lineEdit_12 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.gridLayout.addWidget(self.lineEdit_12, 3, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.lineEdit_10 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.gridLayout.addWidget(self.lineEdit_10, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 3, 1, 1)
        self.lineEdit_11 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.gridLayout.addWidget(self.lineEdit_11, 3, 0, 1, 1)
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_3)
        self.tabWidget_2.setMinimumSize(QtCore.QSize(0, 422))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButton_6 = QtGui.QPushButton(self.tab_4)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_3.addWidget(self.pushButton_6, 2, 1, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.tab_4)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_3.addWidget(self.checkBox, 4, 1, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.tab_4)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 351))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.gridLayout_3.addWidget(self.tableWidget, 1, 0, 5, 1)
        self.pushButton_7 = QtGui.QPushButton(self.tab_4)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_3.addWidget(self.pushButton_7, 3, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab_4)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 1)
        self.pushButton_15 = QtGui.QPushButton(self.tab_4)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.gridLayout_3.addWidget(self.pushButton_15, 1, 1, 1, 1)
        self.label.raise_()
        self.lineEdit_9.raise_()
        self.tableWidget.raise_()
        self.label_12.raise_()
        self.pushButton_15.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.checkBox.raise_()
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButton_8 = QtGui.QPushButton(self.tab_5)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_2.addWidget(self.pushButton_8, 1, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab_5)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 1)
        self.tableWidget_2 = QtGui.QTableWidget(self.tab_5)
        self.tableWidget_2.setMinimumSize(QtCore.QSize(0, 351))
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.gridLayout_2.addWidget(self.tableWidget_2, 1, 0, 5, 1)
        self.pushButton_9 = QtGui.QPushButton(self.tab_5)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_2.addWidget(self.pushButton_9, 2, 1, 1, 1)
        self.pushButton_10 = QtGui.QPushButton(self.tab_5)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.gridLayout_2.addWidget(self.pushButton_10, 3, 1, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.tab_5)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_2.addWidget(self.checkBox_2, 4, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_16 = QtGui.QLabel(self.tab_6)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_4.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab_6)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_4.addWidget(self.label_15, 4, 0, 1, 1)
        self.lineEdit_14 = QtGui.QLineEdit(self.tab_6)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.gridLayout_4.addWidget(self.lineEdit_14, 5, 0, 1, 1)
        self.pushButton_12 = QtGui.QPushButton(self.tab_6)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.gridLayout_4.addWidget(self.pushButton_12, 5, 3, 1, 1)
        self.lineEdit_13 = QtGui.QLineEdit(self.tab_6)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.gridLayout_4.addWidget(self.lineEdit_13, 1, 0, 1, 1)
        self.pushButton_11 = QtGui.QPushButton(self.tab_6)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.gridLayout_4.addWidget(self.pushButton_11, 1, 3, 1, 1)
        self.pushButton_14 = QtGui.QPushButton(self.tab_6)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.gridLayout_4.addWidget(self.pushButton_14, 1, 2, 1, 1)
        self.pushButton_13 = QtGui.QPushButton(self.tab_6)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.gridLayout_4.addWidget(self.pushButton_13, 5, 2, 1, 1)
        self.tabWidget_2.addTab(self.tab_6, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget_2, 5, 0, 1, 2)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.spinBox_2 = QtGui.QSpinBox(self.tab_7)
        self.spinBox_2.setMaximumSize(QtCore.QSize(16777215, 24))
        self.spinBox_2.setProperty("value", 4)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.gridLayout_5.addWidget(self.spinBox_2, 4, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.tab_7)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_5.addWidget(self.label_20, 7, 0, 1, 1)
        self.line_4 = QtGui.QFrame(self.tab_7)
        self.line_4.setMinimumSize(QtCore.QSize(0, 301))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_5.addWidget(self.line_4, 0, 1, 12, 1)
        self.label_21 = QtGui.QLabel(self.tab_7)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_5.addWidget(self.label_21, 0, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.tab_7)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_5.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.tab_7)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_5.addWidget(self.label_18, 3, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.tab_7)
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_5.addWidget(self.label_19, 5, 0, 1, 1)
        self.spinBox_3 = QtGui.QSpinBox(self.tab_7)
        self.spinBox_3.setMaximumSize(QtCore.QSize(16777215, 24))
        self.spinBox_3.setProperty("value", 10)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.gridLayout_5.addWidget(self.spinBox_3, 6, 0, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.tab_7)
        self.spinBox.setMaximumSize(QtCore.QSize(16777215, 24))
        self.spinBox.setProperty("value", 13)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_5.addWidget(self.spinBox, 2, 0, 1, 1)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.tab_7)
        self.doubleSpinBox.setMaximumSize(QtCore.QSize(16777215, 24))
        self.doubleSpinBox.setProperty("value", 0.01)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.gridLayout_5.addWidget(self.doubleSpinBox, 8, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab_7)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_5.addWidget(self.label_14, 1, 0, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.tab_7)
        self.pushButton_5.setMaximumSize(QtCore.QSize(16777215, 32))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_5.addWidget(self.pushButton_5, 9, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.tab_7)
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_5.addWidget(self.label_22, 1, 2, 1, 1)
        self.spinBox_4 = QtGui.QSpinBox(self.tab_7)
        self.spinBox_4.setMaximumSize(QtCore.QSize(16777215, 24))
        self.spinBox_4.setProperty("value", 30)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.gridLayout_5.addWidget(self.spinBox_4, 2, 2, 1, 1)
        self.label_23 = QtGui.QLabel(self.tab_7)
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_5.addWidget(self.label_23, 3, 2, 1, 1)
        self.spinBox_5 = QtGui.QSpinBox(self.tab_7)
        self.spinBox_5.setMaximumSize(QtCore.QSize(16777215, 24))
        self.spinBox_5.setProperty("value", 3)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.gridLayout_5.addWidget(self.spinBox_5, 4, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab_7)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_5.addWidget(self.label_24, 5, 2, 1, 1)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.tab_7)
        self.doubleSpinBox_2.setMaximumSize(QtCore.QSize(16777215, 24))
        self.doubleSpinBox_2.setProperty("value", 1.0)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.gridLayout_5.addWidget(self.doubleSpinBox_2, 6, 2, 1, 1)
        self.pushButton_16 = QtGui.QPushButton(self.tab_7)
        self.pushButton_16.setMaximumSize(QtCore.QSize(16777215, 32))
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.gridLayout_5.addWidget(self.pushButton_16, 9, 2, 1, 1)
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))


        self.gridlayout.addWidget(self.tabWidget, 0, 0, 1, 1)


        self.retranslateUi(DialogModelVisualization)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DialogModelVisualization)

    def retranslateUi(self, DialogModelVisualization):
        DialogModelVisualization.setWindowTitle(QtGui.QApplication.translate("DialogModelVisualization", "Preprocess", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonBrowseAtomScore.setText(QtGui.QApplication.translate("DialogModelVisualization", "Volume...", None, QtGui.QApplication.UnicodeUTF8))
        self.preprocessPushButton.setText(QtGui.QApplication.translate("DialogModelVisualization", "Preprocess", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("DialogModelVisualization", "Preprocess", None, QtGui.QApplication.UnicodeUTF8))
        
        self.pushButton_17.setText(_translate("DialogModelVisualization", "Add", None))
        self.pushButton_19.setText(_translate("DialogModelVisualization", "Clear", None))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("DialogModelVisualization", "threshold.belowtominval", None))
        item = self.listWidget.item(1)
        item.setText(_translate("DialogModelVisualization", "threshold.belowtozero_cut", None))
        item = self.listWidget.item(2)
        item.setText(_translate("DialogModelVisualization", "threshold.binary", None))
        item = self.listWidget.item(3)
        item.setText(_translate("DialogModelVisualization", "threshold.binary.fourier", None))
        item = self.listWidget.item(4)
        item.setText(_translate("DialogModelVisualization", "threshold.binaryrange", None))
        item = self.listWidget.item(5)
        item.setText(_translate("DialogModelVisualization", "threshold.clampminmax", None))
        item = self.listWidget.item(6)
        item.setText(_translate("DialogModelVisualization", "threshold.clampminmax.nsigma", None))
        item = self.listWidget.item(7)
        item.setText(_translate("DialogModelVisualization", "threshold.compress", None))
        item = self.listWidget.item(8)
        item.setText(_translate("DialogModelVisualization", "threshold.notzero", None))
        item = self.listWidget.item(9)
        item.setText(_translate("DialogModelVisualization", "normalize.bymass", None))
        item = self.listWidget.item(10)
        item.setText(_translate("DialogModelVisualization", "normalize.circlemean", None))
        item = self.listWidget.item(11)
        item.setText(_translate("DialogModelVisualization", "normalize.local", None))
        item = self.listWidget.item(12)
        item.setText(_translate("DialogModelVisualization", "normalize.ramp.normvar", None))
        item = self.listWidget.item(13)
        item.setText(_translate("DialogModelVisualization", "normalize.lredge", None))
        item = self.listWidget.item(14)
        item.setText(_translate("DialogModelVisualization", "normalize.rows", None))
        item = self.listWidget.item(15)
        item.setText(_translate("DialogModelVisualization", "normalize.maxmin", None))
        item = self.listWidget.item(16)
        item.setText(_translate("DialogModelVisualization", "normalize.mask", None))
        item = self.listWidget.item(17)
        item.setText(_translate("DialogModelVisualization", "normalize.toimage", None))
        item = self.listWidget.item(18)
        item.setText(_translate("DialogModelVisualization", "normalize.unitlen", None))
        item = self.listWidget.item(19)
        item.setText(_translate("DialogModelVisualization", "normalize.unitsum", None))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_18.setText(_translate("DialogModelVisualization", "Remove", None))
        self.label_3.setText(_translate("DialogModelVisualization", "Current Processors", None))
        self.label_25.setText(_translate("DialogModelVisualization", "Available Processors", None))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("DialogModelVisualization", "normalize.edgemean", None))
        item = self.listWidget_2.item(1)
        item.setText(_translate("DialogModelVisualization", "threshold.belowtozero", None))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        #self.pushButton_3.setText(_translate("DialogModelVisualization", "Preprocess", None))
        #self.pushButton.setText(_translate("DialogModelVisualization", "Volume...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DialogModelVisualization", "Preprocess", None))

        #self.label_5.setText(_translate("DialogModelVisualization", "Processor", None))
        self.label_9.setText(_translate("DialogModelVisualization", "Segment Separation", None))
        self.label_7.setText(_translate("DialogModelVisualization", "Amplitude Weight", None))
        self.label_8.setText(_translate("DialogModelVisualization", "Threshold", None))
        self.label_6.setText(_translate("DialogModelVisualization", "Segments", None))
        self.pushButton_2.setText(_translate("DialogModelVisualization", "Generate PseudoAtoms", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("DialogModelVisualization", "Pseudoatom Generation", None))
        self.lineEdit_7.setText(_translate("DialogModelVisualization", "10", None))
        self.lineEdit_8.setText(_translate("DialogModelVisualization", "1", None))
        #self.lineEdit_3.setText(_translate("DialogModelVisualization", "segment.kmeans", None))
        self.lineEdit_6.setText(_translate("DialogModelVisualization", "1", None))
        self.lineEdit_5.setText(_translate("DialogModelVisualization", "1022", None))
        self.lineEdit_9.setText(_translate("DialogModelVisualization", "1", None))

        __sortingEnabled = self.listWidget_4.isSortingEnabled()
        self.listWidget_4.setSortingEnabled(False)
        item = self.listWidget_4.item(0)
        item.setText(_translate("DialogModelVisualization", "segment.distance", None))
        item = self.listWidget_4.item(1)
        item.setText(_translate("DialogModelVisualization", "threshold.belowtominval", None))
        item = self.listWidget_4.item(2)
        item.setText(_translate("DialogModelVisualization", "threshold.belowtozero_cut", None))
        item = self.listWidget_4.item(3)
        item.setText(_translate("DialogModelVisualization", "threshold.binary", None))
        item = self.listWidget_4.item(4)
        item.setText(_translate("DialogModelVisualization", "threshold.binary.fourier", None))
        item = self.listWidget_4.item(5)
        item.setText(_translate("DialogModelVisualization", "threshold.binaryrange", None))
        item = self.listWidget_4.item(6)
        item.setText(_translate("DialogModelVisualization", "threshold.clampminmax", None))
        item = self.listWidget_4.item(7)
        item.setText(_translate("DialogModelVisualization", "threshold.clampminmax.nsigma", None))
        item = self.listWidget_4.item(8)
        item.setText(_translate("DialogModelVisualization", "threshold.compress", None))
        item = self.listWidget_4.item(9)
        item.setText(_translate("DialogModelVisualization", "threshold.notzero", None))
        item = self.listWidget_4.item(10)
        item.setText(_translate("DialogModelVisualization", "normalize.bymass", None))
        item = self.listWidget_4.item(11)
        item.setText(_translate("DialogModelVisualization", "normalize.circlemean", None))
        item = self.listWidget_4.item(12)
        item.setText(_translate("DialogModelVisualization", "normalize.local", None))
        item = self.listWidget_4.item(13)
        item.setText(_translate("DialogModelVisualization", "normalize.ramp.normvar", None))
        item = self.listWidget_4.item(14)
        item.setText(_translate("DialogModelVisualization", "normalize.lredge", None))
        item = self.listWidget_4.item(15)
        item.setText(_translate("DialogModelVisualization", "normalize.rows", None))
        item = self.listWidget_4.item(16)
        item.setText(_translate("DialogModelVisualization", "normalize.maxmin", None))
        item = self.listWidget_4.item(17)
        item.setText(_translate("DialogModelVisualization", "normalize.mask", None))
        item = self.listWidget_4.item(18)
        item.setText(_translate("DialogModelVisualization", "normalize.toimage", None))
        item = self.listWidget_4.item(19)
        item.setText(_translate("DialogModelVisualization", "normalize.unitlen", None))
        item = self.listWidget_4.item(20)
        item.setText(_translate("DialogModelVisualization", "normalize.unitsum", None))
        self.listWidget_4.setSortingEnabled(__sortingEnabled)
        self.label_8.setText(_translate("DialogModelVisualization", "Threshold", None))
        __sortingEnabled = self.listWidget_3.isSortingEnabled()
        self.listWidget_3.setSortingEnabled(False)
        item = self.listWidget_3.item(0)
        item.setText(_translate("DialogModelVisualization", "segment.kmeans", None))
        self.listWidget_3.setSortingEnabled(__sortingEnabled)
        #self.pushButton_2.setText(_translate("DialogModelVisualization", "Generate PseudoAtoms", None))
        self.pushButton_22.setText(_translate("DialogModelVisualization", "Clear", None))
        self.label_4.setText(_translate("DialogModelVisualization", "Current Processors", None))
        self.pushButton_20.setText(_translate("DockWidget", "Remove", None))
        self.pushButton_21.setText(_translate("DockWidget", "Add", None))

        self.label.setText(_translate("DialogModelVisualization", "Minimum Distance", None))
        self.label_2.setText(_translate("DialogModelVisualization", "Maximum Distance", None))
        self.lineEdit_9.setText(_translate("DialogModelVisualization", "1", None))
        self.lineEdit_10.setText(_translate("DialogModelVisualization", "10", None))
        self.label_10.setText(_translate("DialogModelVisualization", "Map Threshold", None))
        self.label_11.setText(_translate("DialogModelVisualization", "Map Weight", None))
        self.lineEdit_11.setText(_translate("DialogModelVisualization", "12", None))
        self.lineEdit_12.setText(_translate("DialogModelVisualization", "200", None))
        self.label_12.setText(_translate("DialogModelVisualization", "Prevent edges (Ctrl + left click two atoms):", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DialogModelVisualization", "Atom 1", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DialogModelVisualization", "Atom 2", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DialogModelVisualization", "Distance", None))

        self.pushButton_6.setText(_translate("DialogModelVisualization", "Remove from list", None))
        self.pushButton_7.setText(_translate("DialogModelVisualization", "Clear list", None))
        self.checkBox.setText(_translate("DialogModelVisualization", "Display removed edges", None))
        self.label_13.setText(_translate("DialogModelVisualization", "Force edges (Ctrl + left click two atoms):", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("DialogModelVisualization", "Atom 1", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("DialogModelVisualization", "Atom 2", None))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("DialogModelVisualization", "Distance", None))

        self.pushButton_15.setText(_translate("DialogModelVisualization", "Prevent selected edge", None))
        self.pushButton_8.setText(_translate("DialogModelVisualization", "Force selected edge", None))
        self.pushButton_9.setText(_translate("DialogModelVisualization", "Remove from list", None))
        self.pushButton_10.setText(_translate("DialogModelVisualization", "Clear list", None))
        self.checkBox_2.setText(_translate("DialogModelVisualization", "Display forced edges", None))
        self.label_16.setText(_translate("DialogModelVisualization", "Set N-terminus:", None))
        self.pushButton_11.setText(_translate("DialogModelVisualization", "Set n-terminus as selected", None))
        self.label_15.setText(_translate("DialogModelVisualization", "Set C-terminus:", None))
        self.pushButton_12.setText(_translate("DialogModelVisualization", "Set c-terminus as selected", None))
        self.pushButton_4.setText(_translate("DialogModelVisualization", "Pathwalk", None))
        self.pushButton_13.setText(_translate("DialogModelVisualization", "Reset", None))
        self.pushButton_14.setText(_translate("DialogModelVisualization", "Reset", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("DialogModelVisualization", "Pathwalk", None))

        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("DialogModelVisualization", "Prevent Edges", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("DialogModelVisualization", "Force Edges", None))

        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("DialogModelVisualization", "Set Termini", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("DialogModelVisualization", "Pathwalk", None))
        self.label_20.setText(_translate("DialogModelVisualization", "Bond Angle Threshold", None))
        self.label_21.setText(_translate("DialogModelVisualization", "Strands:", None))
        self.label_17.setText(_translate("DialogModelVisualization", "Helices:", None))
        self.label_18.setText(_translate("DialogModelVisualization", "Minimum Length", None))
        self.label_19.setText(_translate("DialogModelVisualization", "Length Threshold", None))
        self.label_14.setText(_translate("DialogModelVisualization", "Density Threshold", None))
        self.pushButton_5.setText(_translate("DialogModelVisualization", "Find and regularize helices", None))
        self.label_22.setText(_translate("DialogModelVisualization", "Max Sheet Strains", None))
        self.label_23.setText(_translate("DialogModelVisualization", "Minimum Length", None))
        self.label_24.setText(_translate("DialogModelVisualization", "Sheet Score Threshold", None))
        self.pushButton_16.setText(_translate("DialogModelVisualization", "Find and regularize Sheets", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("DialogModelVisualization", "Helices and Sheets", None))
        self.label_5.setText(_translate("DialogModelVisualization", "Runs", None))


from colored_push_button import ColoredPushButton
