# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'extremalCurve.ui'
#
# Created by: PyQt4 UI code generator 4.12.dev1605051544
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName(_fromUtf8("DockWidget"))
        DockWidget.resize(423, 571)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 2)
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.tab)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.tab)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.tab)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_2.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.tab)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout_2.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBox.setSingleStep(0.01)
        self.doubleSpinBox.setProperty("value", 1.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.gridLayout_2.addWidget(self.doubleSpinBox, 4, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_2.setSingleStep(0.01)
        self.doubleSpinBox_2.setProperty("value", 50.0)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_2, 5, 1, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.checkBox_22 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_22.setObjectName(_fromUtf8("checkBox_22"))
        self.gridLayout_3.addWidget(self.checkBox_22, 0, 0, 1, 1)
        self.checkBox_24 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_24.setObjectName(_fromUtf8("checkBox_24"))
        self.gridLayout_3.addWidget(self.checkBox_24, 0, 1, 1, 1)
        self.checkBox_23 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_23.setObjectName(_fromUtf8("checkBox_23"))
        self.gridLayout_3.addWidget(self.checkBox_23, 1, 0, 1, 1)
        self.checkBox_25 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_25.setObjectName(_fromUtf8("checkBox_25"))
        self.gridLayout_3.addWidget(self.checkBox_25, 2, 0, 1, 1)
        self.checkBox_26 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_26.setObjectName(_fromUtf8("checkBox_26"))
        self.gridLayout_3.addWidget(self.checkBox_26, 2, 1, 1, 1)
        self.checkBox_21 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_21.setObjectName(_fromUtf8("checkBox_21"))
        self.gridLayout_3.addWidget(self.checkBox_21, 3, 1, 1, 1)
        self.checkBox_27 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_27.setObjectName(_fromUtf8("checkBox_27"))
        self.gridLayout_3.addWidget(self.checkBox_27, 3, 0, 1, 1)
        self.checkBox_4 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.gridLayout_3.addWidget(self.checkBox_4, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalSlider_2 = QtGui.QSlider(self.tab_5)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName(_fromUtf8("horizontalSlider_2"))
        self.gridLayout_4.addWidget(self.horizontalSlider_2, 2, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab_5)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_4.addWidget(self.label_14, 1, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab_5)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_4.addWidget(self.label_13, 1, 0, 1, 1)
        self.checkBox_3 = QtGui.QCheckBox(self.tab_5)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout_4.addWidget(self.checkBox_3, 7, 0, 1, 2)
        self.horizontalSlider_3 = QtGui.QSlider(self.tab_5)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName(_fromUtf8("horizontalSlider_3"))
        self.gridLayout_4.addWidget(self.horizontalSlider_3, 2, 3, 1, 1)
        self.horizontalSlider_5 = QtGui.QSlider(self.tab_5)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName(_fromUtf8("horizontalSlider_5"))
        self.gridLayout_4.addWidget(self.horizontalSlider_5, 7, 2, 1, 2)
        self.checkBox = QtGui.QCheckBox(self.tab_5)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_4.addWidget(self.checkBox, 0, 0, 1, 2)
        self.checkBox_2 = QtGui.QCheckBox(self.tab_5)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_4.addWidget(self.checkBox_2, 3, 0, 1, 2)
        self.label_15 = QtGui.QLabel(self.tab_5)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_4.addWidget(self.label_15, 1, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_5)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 4, 0, 1, 1)
        self.horizontalSlider = QtGui.QSlider(self.tab_5)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.gridLayout_4.addWidget(self.horizontalSlider, 2, 0, 1, 1)
        self.horizontalSlider_4 = QtGui.QSlider(self.tab_5)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName(_fromUtf8("horizontalSlider_4"))
        self.gridLayout_4.addWidget(self.horizontalSlider_4, 4, 1, 1, 3)
        self.horizontalSlider_6 = QtGui.QSlider(self.tab_5)
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName(_fromUtf8("horizontalSlider_6"))
        self.gridLayout_4.addWidget(self.horizontalSlider_6, 5, 1, 1, 3)
        self.label_8 = QtGui.QLabel(self.tab_5)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 5, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(_translate("DockWidget", "DockWidget", None))
        self.pushButton.setText(_translate("DockWidget", "Run Extremal Curve", None))
        self.label.setText(_translate("DockWidget", "Width", None))
        self.lineEdit.setText(_translate("DockWidget", "256", None))
        self.label_2.setText(_translate("DockWidget", "Height", None))
        self.lineEdit_2.setText(_translate("DockWidget", "256", None))
        self.label_3.setText(_translate("DockWidget", "Slices", None))
        self.lineEdit_3.setText(_translate("DockWidget", "50", None))
        self.label_4.setText(_translate("DockWidget", "Grid Resolution", None))
        self.lineEdit_4.setText(_translate("DockWidget", "40", None))
        self.label_5.setText(_translate("DockWidget", "Slices Thickness", None))
        self.label_6.setText(_translate("DockWidget", "Isovalue", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DockWidget", "Load", None))
        self.checkBox_22.setText(_translate("DockWidget", "Max Curve", None))
        self.checkBox_24.setText(_translate("DockWidget", "Min Curve", None))
        self.checkBox_23.setText(_translate("DockWidget", "Saddle Curve", None))
        self.checkBox_25.setText(_translate("DockWidget", "Min Surface", None))
        self.checkBox_26.setText(_translate("DockWidget", "Max Surface", None))
        self.checkBox_21.setText(_translate("DockWidget", "Min Point", None))
        self.checkBox_27.setText(_translate("DockWidget", "Max Point", None))
        self.checkBox_4.setText(_translate("DockWidget", "Saddle Point", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("DockWidget", "Result", None))
        self.label_14.setText(_translate("DockWidget", "Curve:", None))
        self.label_13.setText(_translate("DockWidget", "Point:", None))
        self.checkBox_3.setText(_translate("DockWidget", "Eigenvalue", None))
        self.checkBox.setText(_translate("DockWidget", "Saliency Ratio", None))
        self.checkBox_2.setText(_translate("DockWidget", "Local Intensity", None))
        self.label_15.setText(_translate("DockWidget", "Surface:", None))
        self.label_7.setText(_translate("DockWidget", "Minimum", None))
        self.label_8.setText(_translate("DockWidget", "Maximum", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("DockWidget", "Display", None))

