# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dialog_model_visualization_copy.ui'
#
# Created by: PyQt4 UI code generator 4.12.dev1605051544
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogModelVisualization(object):
    def setupUi(self, DialogModelVisualization):
        DialogModelVisualization.setObjectName(_fromUtf8("DialogModelVisualization"))
        DialogModelVisualization.resize(493, 661)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogModelVisualization.sizePolicy().hasHeightForWidth())
        DialogModelVisualization.setSizePolicy(sizePolicy)
        self.gridlayout = QtGui.QGridLayout(DialogModelVisualization)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.pushButton_7 = QtGui.QPushButton(DialogModelVisualization)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridlayout.addWidget(self.pushButton_7, 11, 0, 1, 1)
        self.label_15 = QtGui.QLabel(DialogModelVisualization)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridlayout.addWidget(self.label_15, 12, 0, 1, 1)
        self.label_14 = QtGui.QLabel(DialogModelVisualization)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridlayout.addWidget(self.label_14, 9, 0, 1, 1)
        self.lineEdit_13 = QtGui.QLineEdit(DialogModelVisualization)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.gridlayout.addWidget(self.lineEdit_13, 2, 0, 1, 1)
        self.label_13 = QtGui.QLabel(DialogModelVisualization)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridlayout.addWidget(self.label_13, 6, 0, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(DialogModelVisualization)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridlayout.addWidget(self.pushButton_6, 8, 0, 1, 1)
        self.lineEdit_14 = QtGui.QLineEdit(DialogModelVisualization)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.gridlayout.addWidget(self.lineEdit_14, 7, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(DialogModelVisualization)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.tab)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout.addWidget(self.pushButton_3, 5, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.tab)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.tab)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 4, 0, 1, 2)
        self.lineEdit_4 = QtGui.QLineEdit(self.tab)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout.addWidget(self.lineEdit_4, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridlayout1 = QtGui.QGridLayout(self.tab_2)
        self.gridlayout1.setMargin(0)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridlayout1.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridlayout1.addWidget(self.label_9, 8, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridlayout1.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridlayout1.addWidget(self.label_8, 6, 0, 1, 1)
        self.lineEdit_7 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.gridlayout1.addWidget(self.lineEdit_7, 6, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridlayout1.addWidget(self.label_6, 4, 0, 1, 1)
        self.lineEdit_8 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridlayout1.addWidget(self.lineEdit_8, 8, 1, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridlayout1.addWidget(self.lineEdit_3, 3, 1, 1, 1)
        self.lineEdit_6 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridlayout1.addWidget(self.lineEdit_6, 5, 1, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridlayout1.addWidget(self.lineEdit_5, 4, 1, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.tab_2)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridlayout1.addWidget(self.pushButton_2, 9, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridlayout2 = QtGui.QGridLayout(self.tab_3)
        self.gridlayout2.setMargin(0)
        self.gridlayout2.setObjectName(_fromUtf8("gridlayout2"))
        self.lineEdit_9 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridlayout2.addWidget(self.lineEdit_9, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridlayout2.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEdit_11 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.gridlayout2.addWidget(self.lineEdit_11, 5, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridlayout2.addWidget(self.label_11, 6, 0, 1, 1)
        self.lineEdit_10 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.gridlayout2.addWidget(self.lineEdit_10, 3, 0, 1, 1)
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridlayout2.addWidget(self.label, 0, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridlayout2.addWidget(self.label_10, 4, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout2.addItem(spacerItem1, 11, 0, 1, 1)
        self.lineEdit_12 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.gridlayout2.addWidget(self.lineEdit_12, 7, 0, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.tab_3)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridlayout2.addWidget(self.pushButton_4, 8, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridlayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.label_12 = QtGui.QLabel(DialogModelVisualization)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridlayout.addWidget(self.label_12, 1, 0, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(DialogModelVisualization)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridlayout.addWidget(self.pushButton_8, 14, 0, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(DialogModelVisualization)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridlayout.addWidget(self.pushButton_5, 5, 0, 1, 1)
        self.lineEdit_15 = QtGui.QLineEdit(DialogModelVisualization)
        self.lineEdit_15.setText(_fromUtf8(""))
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.gridlayout.addWidget(self.lineEdit_15, 10, 0, 1, 1)
        self.lineEdit_16 = QtGui.QLineEdit(DialogModelVisualization)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.gridlayout.addWidget(self.lineEdit_16, 13, 0, 1, 1)

        self.retranslateUi(DialogModelVisualization)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(DialogModelVisualization)

    def retranslateUi(self, DialogModelVisualization):
        DialogModelVisualization.setWindowTitle(_translate("DialogModelVisualization", "Visualization", None))
        self.pushButton_7.setText(_translate("DialogModelVisualization", "Set selected pseudoatom as C-Terminus", None))
        self.label_15.setText(_translate("DialogModelVisualization", "Set N-Terminus:", None))
        self.label_14.setText(_translate("DialogModelVisualization", "Set C-Terminus:", None))
        self.lineEdit_13.setText(_translate("DialogModelVisualization", "bondToRemove", None))
        self.label_13.setText(_translate("DialogModelVisualization", "Bond to create (Ctrl + left click two pseudoatoms):", None))
        self.pushButton_6.setText(_translate("DialogModelVisualization", "Create Bond", None))
        self.lineEdit_14.setText(_translate("DialogModelVisualization", "bondToCreate", None))
        self.label_4.setText(_translate("DialogModelVisualization", "Processor 2", None))
        self.pushButton_3.setText(_translate("DialogModelVisualization", "Preprocess", None))
        self.label_3.setText(_translate("DialogModelVisualization", "Processor 1", None))
        self.pushButton.setText(_translate("DialogModelVisualization", "Volume...", None))
        self.lineEdit_2.setText(_translate("DialogModelVisualization", "threshold.belowtozero", None))
        self.lineEdit_4.setText(_translate("DialogModelVisualization", "normalize.edgemean", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DialogModelVisualization", "Visualization", None))
        self.label_5.setText(_translate("DialogModelVisualization", "Process", None))
        self.label_9.setText(_translate("DialogModelVisualization", "Segment Separation", None))
        self.label_7.setText(_translate("DialogModelVisualization", "Segments", None))
        self.label_8.setText(_translate("DialogModelVisualization", "Threshold", None))
        self.lineEdit_7.setText(_translate("DialogModelVisualization", "10", None))
        self.label_6.setText(_translate("DialogModelVisualization", "Amplitude Weight", None))
        self.lineEdit_8.setText(_translate("DialogModelVisualization", "1", None))
        self.lineEdit_3.setText(_translate("DialogModelVisualization", "segment.kmeans", None))
        self.lineEdit_6.setText(_translate("DialogModelVisualization", "1022", None))
        self.lineEdit_5.setText(_translate("DialogModelVisualization", "1", None))
        self.pushButton_2.setText(_translate("DialogModelVisualization", "Generate PseudoAtoms", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("DialogModelVisualization", "Positioning", None))
        self.lineEdit_9.setText(_translate("DialogModelVisualization", "1", None))
        self.label_2.setText(_translate("DialogModelVisualization", "Maximum Distance", None))
        self.lineEdit_11.setText(_translate("DialogModelVisualization", "12", None))
        self.label_11.setText(_translate("DialogModelVisualization", "Map Weight", None))
        self.lineEdit_10.setText(_translate("DialogModelVisualization", "10", None))
        self.label.setText(_translate("DialogModelVisualization", "Minimum Distance", None))
        self.label_10.setText(_translate("DialogModelVisualization", "Map Threshold", None))
        self.lineEdit_12.setText(_translate("DialogModelVisualization", "200", None))
        self.pushButton_4.setText(_translate("DialogModelVisualization", "Pathwalk", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("DialogModelVisualization", "Properties", None))
        self.label_12.setText(_translate("DialogModelVisualization", "Bonds to remove (Ctrl + left click to select multiple bonds):", None))
        self.pushButton_8.setText(_translate("DialogModelVisualization", "Set selected pseudoatom as N-Terminus", None))
        self.pushButton_5.setText(_translate("DialogModelVisualization", "Remove Selected Bonds", None))

