# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pathwalker_revised.ui'
#
# Created by: PyQt4 UI code generator 4.12.dev1605051544
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName(_fromUtf8("DockWidget"))
        DockWidget.resize(499, 747)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.formLayout = QtGui.QFormLayout(self.dockWidgetContents)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 100, 70, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.pushButton_3 = QtGui.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(14, 155, 361, 32))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.lineEdit = QtGui.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(20, 12, 261, 21))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(280, 10, 97, 32))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 124, 351, 21))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_4 = QtGui.QLineEdit(self.tab)
        self.lineEdit_4.setGeometry(QtCore.QRect(20, 70, 351, 21))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 70, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self._2 = QtGui.QGridLayout(self.tab_2)
        self._2.setMargin(0)
        self._2.setObjectName(_fromUtf8("_2"))
        self.lineEdit_6 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self._2.addWidget(self.lineEdit_6, 5, 1, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.tab_2)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self._2.addWidget(self.pushButton_2, 9, 0, 1, 2)
        self.lineEdit_5 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self._2.addWidget(self.lineEdit_5, 4, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self._2.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self._2.addWidget(self.label_9, 8, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self._2.addWidget(self.label_8, 6, 0, 1, 1)
        self.lineEdit_7 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self._2.addWidget(self.lineEdit_7, 6, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self._2.addWidget(self.label_6, 4, 0, 1, 1)
        self.lineEdit_8 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self._2.addWidget(self.lineEdit_8, 8, 1, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self._2.addWidget(self.lineEdit_3, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self._2.addWidget(self.label_5, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2)
        self.label_2 = QtGui.QLabel(self.tab_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.lineEdit_9 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout_2.addWidget(self.lineEdit_9, 1, 0, 1, 2)
        self.lineEdit_10 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.gridLayout_2.addWidget(self.lineEdit_10, 1, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 2, 2, 1, 1)
        self.lineEdit_11 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.gridLayout_2.addWidget(self.lineEdit_11, 3, 0, 1, 2)
        self.lineEdit_12 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.gridLayout_2.addWidget(self.lineEdit_12, 3, 2, 1, 1)
        self.line = QtGui.QFrame(self.tab_3)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 4, 0, 1, 3)
        self.label_12 = QtGui.QLabel(self.tab_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 5, 0, 1, 3)
        self.tableWidget = QtGui.QTableWidget(self.tab_3)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.gridLayout_2.addWidget(self.tableWidget, 6, 0, 1, 3)
        self.pushButton_5 = QtGui.QPushButton(self.tab_3)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_2.addWidget(self.pushButton_5, 7, 0, 1, 2)
        self.pushButton_6 = QtGui.QPushButton(self.tab_3)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_2.addWidget(self.pushButton_6, 7, 2, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.tab_3)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_2.addWidget(self.pushButton_7, 8, 0, 1, 2)
        self.checkBox = QtGui.QCheckBox(self.tab_3)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_2.addWidget(self.checkBox, 8, 2, 1, 1)
        self.line_2 = QtGui.QFrame(self.tab_3)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 9, 0, 1, 3)
        self.label_13 = QtGui.QLabel(self.tab_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 10, 0, 1, 3)
        self.tableWidget_2 = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.gridLayout_2.addWidget(self.tableWidget_2, 11, 0, 1, 3)
        self.pushButton_8 = QtGui.QPushButton(self.tab_3)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_2.addWidget(self.pushButton_8, 12, 0, 1, 2)
        self.pushButton_9 = QtGui.QPushButton(self.tab_3)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_2.addWidget(self.pushButton_9, 12, 2, 1, 1)
        self.pushButton_10 = QtGui.QPushButton(self.tab_3)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.gridLayout_2.addWidget(self.pushButton_10, 13, 0, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_2.addWidget(self.checkBox_2, 13, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 14, 0, 1, 2)
        self.lineEdit_13 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.gridLayout_2.addWidget(self.lineEdit_13, 15, 0, 1, 1)
        self.pushButton_11 = QtGui.QPushButton(self.tab_3)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.gridLayout_2.addWidget(self.pushButton_11, 15, 1, 1, 2)
        self.label_15 = QtGui.QLabel(self.tab_3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 16, 0, 1, 2)
        self.pushButton_12 = QtGui.QPushButton(self.tab_3)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.gridLayout_2.addWidget(self.pushButton_12, 17, 1, 1, 2)
        self.pushButton_4 = QtGui.QPushButton(self.tab_3)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_2.addWidget(self.pushButton_4, 18, 0, 1, 1)
        self.lineEdit_14 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.gridLayout_2.addWidget(self.lineEdit_14, 17, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.tabWidget)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(_translate("DockWidget", "DockWidget", None))
        self.label_4.setText(_translate("DockWidget", "Processor 2", None))
        self.pushButton_3.setText(_translate("DockWidget", "Preprocess", None))
        self.pushButton.setText(_translate("DockWidget", "Volume...", None))
        self.lineEdit_2.setText(_translate("DockWidget", "threshold.belowtozero", None))
        self.lineEdit_4.setText(_translate("DockWidget", "normalize.edgemean", None))
        self.label_3.setText(_translate("DockWidget", "Processor 1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DockWidget", "Visualization", None))
        self.lineEdit_6.setText(_translate("DockWidget", "1022", None))
        self.pushButton_2.setText(_translate("DockWidget", "Generate PseudoAtoms", None))
        self.lineEdit_5.setText(_translate("DockWidget", "1", None))
        self.label_7.setText(_translate("DockWidget", "Segments", None))
        self.label_9.setText(_translate("DockWidget", "Segment Separation", None))
        self.label_8.setText(_translate("DockWidget", "Threshold", None))
        self.lineEdit_7.setText(_translate("DockWidget", "10", None))
        self.label_6.setText(_translate("DockWidget", "Amplitude Weight", None))
        self.lineEdit_8.setText(_translate("DockWidget", "1", None))
        self.lineEdit_3.setText(_translate("DockWidget", "segment.kmeans", None))
        self.label_5.setText(_translate("DockWidget", "Process", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("DockWidget", "Positioning", None))
        self.label.setText(_translate("DockWidget", "Minimum Distance", None))
        self.label_2.setText(_translate("DockWidget", "Maximum Distance", None))
        self.lineEdit_9.setText(_translate("DockWidget", "1", None))
        self.lineEdit_10.setText(_translate("DockWidget", "10", None))
        self.label_10.setText(_translate("DockWidget", "Map Threshold", None))
        self.label_11.setText(_translate("DockWidget", "Map Weight", None))
        self.lineEdit_11.setText(_translate("DockWidget", "12", None))
        self.lineEdit_12.setText(_translate("DockWidget", "200", None))
        self.label_12.setText(_translate("DockWidget", "Prevent edges (Ctrl + left click two atoms):", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DockWidget", "Atom 1", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DockWidget", "Atom 2", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DockWidget", "Distance", None))
        self.pushButton_5.setText(_translate("DockWidget", "Prevent selected edge", None))
        self.pushButton_6.setText(_translate("DockWidget", "Remove from list", None))
        self.pushButton_7.setText(_translate("DockWidget", "Clear list", None))
        self.checkBox.setText(_translate("DockWidget", "Display removed edges", None))
        self.label_13.setText(_translate("DockWidget", "Force edges (Ctrl + left click two atoms):", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("DockWidget", "Atom 1", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("DockWidget", "Atom 2", None))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("DockWidget", "Distance", None))
        self.pushButton_8.setText(_translate("DockWidget", "Force selected edge", None))
        self.pushButton_9.setText(_translate("DockWidget", "Remove from list", None))
        self.pushButton_10.setText(_translate("DockWidget", "Clear list", None))
        self.checkBox_2.setText(_translate("DockWidget", "Display forced edges", None))
        self.label_14.setText(_translate("DockWidget", "Current C-terminus:", None))
        self.pushButton_11.setText(_translate("DockWidget", "Set c-terminus as selected", None))
        self.label_15.setText(_translate("DockWidget", "Current N-terminus", None))
        self.pushButton_12.setText(_translate("DockWidget", "Set n-terminus as selected", None))
        self.pushButton_4.setText(_translate("DockWidget", "Pathwalk", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("DockWidget", "Properties", None))

